/**
 * Build the helmet the agent mark is drawn from.
 *
 * Writes two files into src/renderer/components/assistant/helmet/:
 *
 * - `mesh.js`: the model, packed (see `pack.mjs`), as one base64 string. The
 *   renderer loads it on first use and draws it live.
 * - `still.js`: the helmet drawn once in its resting pose as SVG paths, for
 *   where there is no WebGL2 (see `fallback.mjs`).
 *
 * Not part of the app's build: the output is committed, and this is only run
 * again when the model or the way it is taken apart changes. It downloads the
 * model once (see `source.mjs`) and needs three packages the app does not, so
 * they are not in package.json:
 *
 *   npm i --no-save potrace pngjs fit-curve
 *   node scripts/helmets/build.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SOURCE, fetchSource, loadHelmet } from './source.mjs';
import { pack, CREST, PATCH, INSIDE } from './pack.mjs';
import { drawStill } from './fallback.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.join(here, '..', '..');
const out = path.join(repo, 'src', 'renderer', 'components', 'assistant', 'helmet');

const credit = `/*!
 * ${SOURCE.title} by ${SOURCE.author}, ${SOURCE.url}
 * Licensed ${SOURCE.licence}: ${SOURCE.licenceUrl}
 * Changed for Acestes: re-oriented, scaled, the crest separated so it can be
 * taken off and the helmet closed where it stood, strands drawn on the crest.
 */`;

const stl = await fetchSource(path.join(here, '.cache'));
const mesh = loadHelmet(stl);
const { buffer, flags, faces, stats } = pack(mesh);
console.log('packed', JSON.stringify(stats));

fs.writeFileSync(path.join(out, 'mesh.js'), `${credit}
// Generated by scripts/helmets/build.mjs. Do not edit.
export default '${buffer.toString('base64')}';
`);

const still = {};
for (const [crest, keep] of [['plume', flag => !(flag & PATCH)], ['none', flag => !(flag & CREST)]]) {
    const list = faces.map((face, i) => i).filter(i => keep(flags[i]));
    still[crest] = await drawStill(mesh.verts, list.map(i => faces[i]), list.map(i => Boolean(flags[i] & INSIDE)));
    console.log('drew', crest, still[crest].lines.length, 'lines');
}
fs.writeFileSync(path.join(out, 'still.js'), `${credit}
// Generated by scripts/helmets/build.mjs. Do not edit.
/* eslint-disable max-len */
export default ${JSON.stringify(still, null, 4)};
`);
console.log('wrote', path.relative(repo, out));
