/**
 * Build the helmets the agent mark is drawn from.
 *
 * Writes into src/renderer/components/assistant/helmet/:
 *
 * - `meshes/<helmet>.js`: each model, packed (see `pack.mjs`), as one base64
 *   string, and as `crests` the crests fitted to it (see `crests.mjs`). The
 *   renderer loads one the first time a mark wears it and draws it live.
 * - `still.js`: every helmet in every crest drawn once in its resting pose
 *   as SVG paths, for where there is no WebGL2 (see `fallback.mjs`).
 *
 * The Corinthian is `source.mjs`, the other helmets `catalogue.mjs`.
 *
 * Not part of the app's build: the output is committed, and this is only run
 * again when a model or the way it is taken apart changes. It downloads each
 * model once and needs four packages the app does not, so they are not in
 * package.json:
 *
 *   npm i --no-save potrace pngjs fit-curve meshoptimizer
 *   node scripts/helmets/build.mjs
 *
 * With --meshes-only it leaves still.js alone, which is quicker for trying a fit.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SOURCE, fetchSource, loadHelmet } from './source.mjs';
import { HELMETS, LICENCE } from './catalogue.mjs';
import { fetchModel } from './gltf.mjs';
import { loadModel } from './model.mjs';
import { CREST_SOURCES, CREST_IDS, loadCrestSources, crestsFor } from './crests.mjs';
import { pack, packModel, packPiece, CREST, PATCH, INSIDE } from './pack.mjs';
import { drawStill } from './fallback.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.join(here, '..', '..');
const out = path.join(repo, 'src', 'renderer', 'components', 'assistant', 'helmet');
const cache = path.join(here, '.cache');
const meshesOnly = process.argv.includes('--meshes-only');

const corinthianCredit = `/*!
 * ${SOURCE.title} by ${SOURCE.author}, ${SOURCE.url}
 * Licensed ${SOURCE.licence}: ${SOURCE.licenceUrl}
 * Changed for Acestes: re-oriented, scaled, the crest separated so it can be
 * taken off and the helmet closed where it stood, strands drawn on the crest.
 */`;
const credit = helmet => `/*!
 * ${helmet.title} by ${helmet.author}, ${helmet.url}
 * Licensed ${LICENCE.name}: ${LICENCE.url}
 * Changed for Acestes: re-oriented, scaled, simplified, drawn as line art.
 */`;
const crestCredit = `/*!
 * The crests: the Corinthian's, from ${SOURCE.title} by ${SOURCE.author} (above
 * or in corinthian.js); ${Object.values(CREST_SOURCES).map(s => `${s.title} by ${s.author}, ${s.url}, licensed ${s.licence}: ${s.licenceUrl}`).join('; ')}.
 * Changed for Acestes: simplified, and bent, stretched or placed to fit the helmet.
 */`;

fs.mkdirSync(path.join(out, 'meshes'), { recursive: true });
const base64 = buffer => `'${buffer.toString('base64')}'`;
function writeMesh(id, header, buffer, crests) {
    const entries = Object.entries(crests).map(([crest, piece]) => `    ${crest}: ${base64(piece)},`);
    fs.writeFileSync(path.join(out, 'meshes', `${id}.js`), `${header}
${crestCredit}
// Generated by scripts/helmets/build.mjs. Do not edit.
export default ${base64(buffer)};
export const crests = {
${entries.join('\n')}
};
`);
}

const still = {};
/**
 * The resting pose drawn for each crest the helmet wears: its own, and each
 * fitted one standing on the helmet without it.
 */
async function drawAll(id, verts, packed, own, fitted) {
    still[id] = {};
    const { faces, flags } = packed;
    const drawings = own.map(([crest, keep]) => {
        const list = faces.map((face, i) => i).filter(i => keep(flags[i]));
        return [crest, verts, list.map(i => faces[i]), list.map(i => Boolean(flags[i] & INSIDE))];
    });
    const bare = drawings.find(([crest]) => crest === 'none');
    for (const [crest, piece] of Object.entries(fitted)) {
        const [, , bareFaces, bareInside] = bare;
        drawings.push([crest, verts.concat(piece.verts),
            bareFaces.concat(piece.faces.map(face => face.map(v => v + verts.length))),
            bareInside.concat(piece.faces.map(() => false))]);
    }
    if (meshesOnly) return;
    for (const [crest, allVerts, list, inside] of drawings) {
        still[id][crest] = await drawStill(allVerts, list, inside);
        console.log('drew', id, crest, still[id][crest].lines.length, 'lines');
    }
}

const mesh = loadHelmet(await fetchSource(cache));
const sources = await loadCrestSources(mesh, cache);

const corinthian = pack(mesh);
console.log('packed corinthian', JSON.stringify(corinthian.stats));
const corinthianBody = corinthian.faces.filter((face, i) => !(corinthian.flags[i] & CREST));
const corinthianCrests = crestsFor(sources, mesh.verts, corinthianBody, ['plume']);
writeMesh('corinthian', corinthianCredit, corinthian.buffer, Object.fromEntries(Object.entries(corinthianCrests).map(([k, p]) => [k, packPiece(p).buffer])));
await drawAll('corinthian', mesh.verts, corinthian, [['plume', flag => !(flag & PATCH)], ['none', flag => !(flag & CREST)]], corinthianCrests);

for (const helmet of HELMETS) {
    const model = await loadModel(helmet, await fetchModel(helmet, cache), { faces: helmet.faces });
    const packed = packModel(model);
    console.log('packed', helmet.id, JSON.stringify(packed.stats));
    const own = helmet.bare ? CREST_IDS : helmet.crest ? ['plume'] : [];
    const fitted = crestsFor(sources, model.verts, model.faces.filter((face, i) => !model.crest[i]), own);
    writeMesh(helmet.id, credit(helmet), packed.buffer, Object.fromEntries(Object.entries(fitted).map(([k, p]) => [k, packPiece(p).buffer])));
    const crests = helmet.crest ? [['plume', () => true], ['none', flag => !(flag & CREST)]] : [['none', () => true]];
    await drawAll(helmet.id, model.verts, packed, crests, fitted);
}

if (!meshesOnly) fs.writeFileSync(path.join(out, 'still.js'), `${[corinthianCredit, ...HELMETS.map(credit), crestCredit].join('\n')}
// Generated by scripts/helmets/build.mjs. Do not edit.
/* eslint-disable max-len */
export default ${JSON.stringify(still, null, 4)};
`);
console.log('wrote', path.relative(repo, out));
